// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Helpers to read env safely and fail fast when required values are missing
  static String _req(String key) {
    final v = dotenv.env[key];
    if (v == null || v.trim().isEmpty) {
      throw StateError('Missing required env: ' + key + ' (check your .env and dotenv.load)');
    }
    return v;
  }

  static String? _opt(String key) {
    final v = dotenv.env[key];
    if (v == null || v.trim().isEmpty) return null;
    return v;
  }
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _req('WEB_API_KEY'),
    appId: _req('WEB_APP_ID'),
    messagingSenderId: _req('WEB_MESSAGING_SENDER_ID'),
    projectId: _req('WEB_PROJECT_ID'),
    authDomain: _opt('WEB_AUTH_DOMAIN'),
    storageBucket: _opt('WEB_STORAGE_BUCKET'),
    measurementId: _opt('WEB_MEASUREMENT_ID'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _req('ANDROID_API_KEY'),
    appId: _req('ANDROID_APP_ID'),
    messagingSenderId: _req('ANDROID_MESSAGING_SENDER_ID'),
    projectId: _req('ANDROID_PROJECT_ID'),
    storageBucket: _opt('ANDROID_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _req('IOS_API_KEY'),
    appId: _req('IOS_APP_ID'),
    messagingSenderId: _req('IOS_MESSAGING_SENDER_ID'),
    projectId: _req('IOS_PROJECT_ID'),
    storageBucket: _opt('IOS_STORAGE_BUCKET'),
    iosBundleId: _opt('IOS_BUNDLE_ID'),
  );
}
