// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCkNnVGk8jL3unVsA-jPwLbQvGZ8xMz4k',
    appId: '1:568264094179:web:c4d30122f82ed4f4daf0d6',
    messagingSenderId: '568264094179',
    projectId: 'cipta-vera-mandiri-digital',
    authDomain: 'cipta-vera-mandiri-digital.firebaseapp.com',
    storageBucket: 'cipta-vera-mandiri-digital.firebasestorage.app',
    measurementId: 'G-TEHV89VX63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxyKYoZaAM10yIEjHxACYva9v-EpHrczw',
    appId: '1:568264094179:android:3a17be497857aacddaf0d6',
    messagingSenderId: '568264094179',
    projectId: 'cipta-vera-mandiri-digital',
    storageBucket: 'cipta-vera-mandiri-digital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32I3_tGfLlPs7pc2sfMzkjQS92GC1n_A',
    appId: '1:568264094179:ios:0dfb1b7211370b06daf0d6',
    messagingSenderId: '568264094179',
    projectId: 'cipta-vera-mandiri-digital',
    storageBucket: 'cipta-vera-mandiri-digital.firebasestorage.app',
    iosBundleId: 'veramandiri.com.ciptaVeraMandiriDigital',
  );
}
