import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:cipta_vera_mandiri_digital/app/routes/app_routes.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'app/routes/app_pages.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  // Debug: verify env values are loaded
  debugPrint('ENV IOS_APP_ID: ' + (dotenv.env['IOS_APP_ID'] ?? 'NULL'));
  debugPrint('ENV IOS_PROJECT_ID: ' + (dotenv.env['IOS_PROJECT_ID'] ?? 'NULL'));
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('✅ Firebase initialized with projectId=' + DefaultFirebaseOptions.currentPlatform.projectId +
        ', appId=' + DefaultFirebaseOptions.currentPlatform.appId);
  } catch (e, st) {
    debugPrint('❌ Firebase init failed: ' + e.toString());
    debugPrint(st.toString());
  }
  runApp(
    GetMaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: Routes.LOGIN,
      getPages: AppPages.routes,
    ),
  );
}
